version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.12.18
    steps:
      - checkout
      - run:
          name: terraform
          command: |
            terraform init \
              -input=false \
              -force-copy \
              -backend-config="token=${terraform_backend_token}" \
              -backend-config="organization=${terraform_backend_organisation}" \
              ./terraform
            terraform plan \
              -input=false \
              -out tfplan \
              -var-file ./terraform/terraform.tfvars \
              -var="docker_ssh_host=${docker_ssh_host}" \
              -var="docker_ssh_port=${docker_ssh_port}" \
              ./terraform
            terraform apply \
              -input=false \
              tfplan
