version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.12.18
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Keyscan
          command: |
            ssh-keyscan -p ${docker_ssh_port} -H ${docker_ssh_host} >> ~/.ssh/known_hosts
      - run:
          name: terraform
          command: |
            terraform init \
              -input=false \
              -force-copy \
              -backend-config="token=${terraform_backend_token}" \
              -backend-config="organization=${terraform_backend_organisation}" \
              ./terraform
            terraform plan \
              -input=false \
              -out tfplan \
              -var="docker_ssh_host=${docker_ssh_host}" \
              -var="docker_ssh_port=${docker_ssh_port}" \
              -var="domain=${DOMAIN}" \
              -var="portainer_admin_password_hash=${portainer_admin_password_hash}" \
              ./terraform
            terraform apply \
              -input=false \
              tfplan

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: dev-server
