version: '3.4'

services:
  plex:
    image: plexinc/pms-docker
    networks:
      - public-network
    ports:
      - "32400:32400"
    volumes:
      - plex_config:/config
      - media_downloads:/downloads
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.plex.entrypoints=https"
        - "traefik.http.routers.plex.rule=Host(`plex.${domain}`)"
        - "traefik.http.routers.plex.tls.certresolver=le-dns"
        - "traefik.http.routers.plex.tls.domains[0].main=${domain}"
        - "traefik.http.routers.plex.tls.domains[0].sans=*.${domain}"
        - "traefik.http.services.plex.loadbalancer.server.port=32400"

networks:
  public-network:
    external: true
    
volumes:
  plex_config:
  media_downloads:
